### ISSUE TITLE
Notes on Network play

### ISSUE THREAD

**Issue by whoisterencelee** [scottschiller/ArmorAlley#6] opened 2023-07-05 08:35 UTC
Noticed network game play is available, AMAZING, so start testing using grey (right side) helicopter, seems most issues can be seen there :^)
- some items are invisible from grey side, e.g. balloons and units, this happens sometimes, not sure what condition triggers it, but these items don't show on radar or on the play area, only knows when we crash or shot at the invisible item
- most bunkers start from green side, even ones close to grey base, not sure if that's due to the map design
- when dropping troops with grey heli, the troops walks out to the right and get back into heli

Really almost playable, AMAZINGGG

**Comment by scottschiller** [comment] 2023-07-06 01:43
Hello, and thank you for the feedback and report; excellent finds. 🙇‍♂️ 👍

I definitely tested the network play largely as the green / left side player most of the time. 😅 Additionally, the default "human" player stuff has been battle-tested over the years - so it makes sense that the right / grey side could have some bugs, as e.g., I never added "dropping paratroopers" to the CPU / AI.

_(Total side note, I've been meaning to do that when you as the human player fire a smart missile at the enemy chopper - so they might act as decoys or blockers. The original game did this, at some level of difficulty.)_

There might be a de-sync issue around balloons etc., I will look into that. _Ideally_, all objects should be in sync regardless of what side you're on. If you're hitting invisible things, that's not good and something has definitely gone sideways.

I'll review the bunker situation. Depending on the level, that may be correct. I think most of the network games have a decent balance of sides, but I'm not sure that is always the case. If you play the original levels in a network game, keep in mind that those were designed initially for single-player; so earlier on e.g., Cake Walk, the left / green side will have a significant bunker ownership advantage and so forth. I can review the original game and if they allow you to play those levels _and_ they are balanced, then I will do the same.

I suspect I forgot to handle the grey helicopter dropping paratroopers, and/or infantry from the ground. Whoops! Without being positioned to the left, they'll be picked up again by the helicopter. 😅 This should be an easy fix.

Thanks again for the detailed report, this is great detail. And, I hope you enjoyed playing this remake!

**Comment by scottschiller** [comment] 2023-07-07 22:24
@whoisterencelee I pushed some updates earlier, and this is now live on https://play.armor-alley.net - details follow, for the curious.

* Grey helicopter: Releasing infantry on the ground should now work as expected. They should spawn slightly to the left, in front, and not be picked up immediately by the chopper. 😅 I forgot to work in the positioning offset for the grey side, as mentioned.

**Balloon + object de-sync**

* Balloon issue #1: I realized today that I introduced a subtle regression in network logic when I added a "level preview" radar feature some time ago. Basically, the level preview feature was throwing off object ID counting and tracking for the actual network game. When the host selects a level and then starts a network game, its balloon ID offset would be different than the remote client because of the previews - and so then when balloon #1 gets popped on one side, it might cause a totally different balloon on the other side to pop. Whoops! 😅 In some cases, this might contribute to the "invisible object" your helicopter sometimes hits. Very annoying.

* Balloon issue #2: I noticed some balloons drifting over time between clients, where their positioning became de-synced. This is another cause of the "invisible" helicopter crash at times.

In the local game, there's a "random wind" effect where balloons can slow down or speed up. The randomness is where the de-sync can sneak in between clients. I've disabled that for now, so balloons get one random wind x/y velocity at game start, stay on a constant course and only change direction when they hit boundaries. This should keep them in sync, so the positions are consistent.

Thanks again for the detailed report, these are good bugs and the network play should be much more enjoyable now, if there aren't any other wild de-sync issues lurking about. 😅

**Comment by scottschiller** [comment] 2023-07-07 22:32
One thing I forgot: I re-ordered the game level drop-down in the network modal, so that network levels are first. They are designed to be more balanced in terms of who owns bunkers etc., assuming PvP.

I thought it would be fun for people to be able to play the original game levels as network games too, but then "cake walk" has the majority of bunkers being owned by the left (green) side to start. I might add some logic or an option to balance sides as applicable, so each side owns half of the battlefield when a network game starts. That is, unless someone likes a good challenge! ;)

**Comment by scottschiller** [comment] 2023-07-14 16:24
@whoisterencelee: I'm going to close this one as fixed, but please re-open or create a new issue if you feel I missed something from your report. In testing, I believe the balloons are staying in sync during network games and that should now make the game much more reliable. 😅 🎉

**Closed by scottschiller** 2023-07-14 16:24 UTC
